- hosts: all
  gather_facts: no
  remote_user: nanojet
  #become: yes
  tasks:
  - name: "copyfile"
    copy:
     src: /home/nanojet/samtools-1.7/samtools
     dest: /nanopore/bin/samtools
     #owner: root
     #group: root
     mode: 0744

